export default [
  { name: 'Pilih Bank', value: '', disabled: true },
  { name: 'Sinarmas', value: 'Sinarmas' },
  { name: 'Bank Syariah Mandiri', value: 'Bank Syariah Mandiri' },
  { name: 'Bank Tabungan Pensiunan Nasional', value: 'Bank Tabungan Pensiunan Nasional' },
  { name: 'Bank Mandiri', value: 'Bank Mandiri' },
  { name: 'Bank CIMB Niaga', value: 'Bank CIMB Niaga' },
  { name: 'Bank Rakyat Indonesia (BRI)', value: 'Bank Rakyat Indonesia (BRI)' },
  { name: 'Bank Danamon', value: 'Bank Danamon' },
  { name: 'Bank Permata', value: 'Bank Permata' },
  { name: 'Bank Panin', value: 'Bank Panin' },
  { name: 'Bank Maybank', value: 'Bank Maybank' },
  { name: 'Anglomas International Bank', value: 'Anglomas International Bank' },
  { name: 'Bangkok Bank', value: 'Bangkok Bank' },
  { name: 'Bank Agris', value: 'Bank Agris' },
  { name: 'Bank Agroniaga', value: 'Bank Agroniaga' },
  { name: 'Bank Andara', value: 'Bank Andara' },
  { name: 'China Construction Bank Indonesia', value: 'China Construction Bank Indonesia' },
  { name: 'Bank ANZ Indonesia', value: 'Bank ANZ Indonesia' },
  { name: 'Bank Artha Graha International', value: 'Bank Artha Graha International' },
  { name: 'Bank Artos Indonesia', value: 'Bank Artos Indonesia' },
  { name: 'Bank Bisnis Internasional', value: 'Bank Bisnis Internasional' },
  { name: 'Bank BJB Syariah', value: 'Bank BJB Syariah' },
  { name: 'Bank BJB', value: 'Bank BJB' },
  { name: 'Bank BNI Syariah', value: 'Bank BNI Syariah' },
  { name: 'Bank BNP Paribas', value: 'Bank BNP Paribas' },
  { name: 'Bank Bukopin', value: 'Bank Bukopin' },
  { name: 'Bank Bumi Arta', value: 'Bank Bumi Arta' },
  { name: 'Bank Capital Indonesia', value: 'Bank Capital Indonesia' },
  { name: 'Bank Chinatrust Indonesia', value: 'Bank Chinatrust Indonesia' },
  { name: 'Bank CIMB Niaga UUS', value: 'Bank CIMB Niaga UUS' },
  { name: 'Bank Commonwealth', value: 'Bank Commonwealth' },
  { name: 'Bank Danamon UUS', value: 'Bank Danamon UUS' },
  { name: 'Bank DBS Indonesia', value: 'Bank DBS Indonesia' },
  { name: 'Bank Dinar Indonesia', value: 'Bank Dinar Indonesia' },
  { name: 'Bank DKI', value: 'Bank DKI' },
  { name: 'Bank DKI UUS', value: 'Bank DKI UUS' },
  { name: 'HSBC Indonesia', value: 'HSBC Indonesia' },
  { name: 'Bank Fama International', value: 'Bank Fama International' },
  { name: 'Bank Ganesha', value: 'Bank Ganesha' },
  { name: 'Bank Hana', value: 'Bank Hana' },
  { name: 'Bank Harda Internasional', value: 'Bank Harda Internasional' },
  { name: 'Bank Himpunan Saudara 1906', value: 'Bank Himpunan Saudara 1906' },
  { name: 'Bank ICBC Indonesia', value: 'Bank ICBC Indonesia' },
  { name: 'Bank Ina Perdania', value: 'Bank Ina Perdania' },
  { name: 'Bank Index Selindo', value: 'Bank Index Selindo' },
  { name: 'Bank Jasa Jakarta', value: 'Bank Jasa Jakarta' },
  { name: 'Bank Kesejahteraan Ekonomi', value: 'Bank Kesejahteraan Ekonomi' },
  { name: 'Bank Maspion Indonesia', value: 'Bank Maspion Indonesia' },
  { name: 'Bank Mayapada International', value: 'Bank Mayapada International' },
  { name: 'Bank Maybank Syariah Indonesia', value: 'Bank Maybank Syariah Indonesia' },
  { name: 'Bank Mayora', value: 'Bank Mayora' },
  { name: 'Bank Mega', value: 'Bank Mega' },
  { name: 'Bank Mestika Dharma', value: 'Bank Mestika Dharma' },
  { name: 'Bank Shinhan Indonesia', value: 'Bank Shinhan Indonesia' },
  { name: 'Bank MNC Internasional', value: 'Bank MNC Internasional' },
  { name: 'Bank Mizuho Indonesia', value: 'Bank Mizuho Indonesia' },
  { name: 'Bank Muamalat Indonesia', value: 'Bank Muamalat Indonesia' },
  { name: 'Bank Multi Arta Sentosa', value: 'Bank Multi Arta Sentosa' },
  { name: 'Bank JTrust Indonesia', value: 'Bank JTrust Indonesia' },
  { name: 'Bank Nationalnobu', value: 'Bank Nationalnobu' },
  { name: 'Bank OCBC NISP', value: 'Bank OCBC NISP' },
  { name: 'Bank Nusantara Parahyangan', value: 'Bank Nusantara Parahyangan' },
  { name: 'Bank OCBC NISP UUS', value: 'Bank OCBC NISP UUS' },
  { name: 'Bank of America Merill-Lynch', value: 'Bank of America Merill-Lynch' },
  { name: 'Bank of China (BOC)', value: 'Bank of China (BOC)' },
  { name: 'Bank of India Indonesia', value: 'Bank of India Indonesia' },
  { name: 'Bank of Tokyo Mitsubishi UFJ', value: 'Bank of Tokyo Mitsubishi UFJ' },
  { name: 'Bank Panin Syariah', value: 'Bank Panin Syariah' },
  { name: 'Bank Permata UUS', value: 'Bank Permata UUS' },
  { name: 'BPD Banten', value: 'BPD Banten' },
  { name: 'Bank QNB Indonesia', value: 'Bank QNB Indonesia' },
  { name: 'Bank Rabobank International Indonesia', value: 'Bank Rabobank International Indonesia' },
  { name: 'Bank Resona Perdania', value: 'Bank Resona Perdania' },
  { name: 'Bank Royal Indonesia', value: 'Bank Royal Indonesia' },
  { name: 'BTPN Syariah', value: 'BTPN Syariah' },
  { name: 'Bank Sahabat Sampoerna', value: 'Bank Sahabat Sampoerna' },
  { name: 'Mandiri Taspen Pos', value: 'Mandiri Taspen Pos' },
  { name: 'Bank SBI Indonesia', value: 'Bank SBI Indonesia' },
  { name: 'Bank Sumitomo Mitsui Indonesia', value: 'Bank Sumitomo Mitsui Indonesia' },
  { name: 'Bank Syariah BRI', value: 'Bank Syariah BRI' },
  { name: 'Bank Syariah Bukopin', value: 'Bank Syariah Bukopin' },
  { name: 'Bank Syariah Mega', value: 'Bank Syariah Mega' },
  { name: 'Bank Tabungan Negara (BTN)', value: 'Bank Tabungan Negara (BTN)' },
  { name: 'Bank Tabungan Negara (BTN) UUS', value: 'Bank Tabungan Negara (BTN) UUS' },
  { name: 'Bank UOB Indonesia', value: 'Bank UOB Indonesia' },
  { name: 'Bank Victoria Internasional', value: 'Bank Victoria Internasional' },
  { name: 'Bank Victoria Syariah', value: 'Bank Victoria Syariah' },
  { name: 'Bank Woori Indonesia', value: 'Bank Woori Indonesia' },
  { name: 'Bank Yudha Bhakti', value: 'Bank Yudha Bhakti' },
  { name: 'BPD Aceh', value: 'BPD Aceh' },
  { name: 'BPD Aceh UUS', value: 'BPD Aceh UUS' },
  { name: 'BPD Bali', value: 'BPD Bali' },
  { name: 'BPD Bengkulu', value: 'BPD Bengkulu' },
  { name: 'BPD Daerah Istimewa Yogyakarta (DIY)', value: 'BPD Daerah Istimewa Yogyakarta (DIY)' },
  { name: 'BPD Daerah Istimewa Yogyakarta (DIY) UUS', value: 'BPD Daerah Istimewa Yogyakarta (DIY) UUS' },
  { name: 'BPD Jambi', value: 'BPD Jambi' },
  { name: 'BPD Jambi UUS', value: 'BPD Jambi UUS' },
  { name: 'BPD Jawa Tengah', value: 'BPD Jawa Tengah' },
  { name: 'BPD Jawa Tengah UUS', value: 'BPD Jawa Tengah UUS' },
  { name: 'BPD Jawa Timur', value: 'BPD Jawa Timur' },
  { name: 'BPD Jawa Timur UUS', value: 'BPD Jawa Timur UUS' },
  { name: 'BPD Kalimantan Barat', value: 'BPD Kalimantan Barat' },
  { name: 'BPD Kalimantan Barat UUS', value: 'BPD Kalimantan Barat UUS' },
  { name: 'BPD Kalimantan Selatan', value: 'BPD Kalimantan Selatan' },
  { name: 'BPD Kalimantan Selatan UUS', value: 'BPD Kalimantan Selatan UUS' },
  { name: 'BPD Kalimantan Tengah', value: 'BPD Kalimantan Tengah' },
  { name: 'BPD Kalimantan Timur', value: 'BPD Kalimantan Timur' },
  { name: 'BPD Kalimantan Timur UUS', value: 'BPD Kalimantan Timur UUS' },
  { name: 'BPD Lampung', value: 'BPD Lampung' },
  { name: 'BPD Nusa Tenggara Barat', value: 'BPD Nusa Tenggara Barat' },
  { name: 'BPD Maluku', value: 'BPD Maluku' },
  { name: 'BPD Nusa Tenggara Barat UUS', value: 'BPD Nusa Tenggara Barat UUS' },
  { name: 'BPD Nusa Tenggara Timur', value: 'BPD Nusa Tenggara Timur' },
  { name: 'BPD Papua', value: 'BPD Papua' },
  { name: 'BPD Riau Dan Kepri', value: 'BPD Riau Dan Kepri' },
  { name: 'BPD Riau Dan Kepri UUS', value: 'BPD Riau Dan Kepri UUS' },
  { name: 'BPD Sulawesi Tengah', value: 'BPD Sulawesi Tengah' },
  { name: 'BPD Sulawesi Tenggara', value: 'BPD Sulawesi Tenggara' },
  { name: 'BPD Sulselbar', value: 'BPD Sulselbar' },
  { name: 'BPD Sulselbar UUS', value: 'BPD Sulselbar UUS' },
  { name: 'BPD Sulut', value: 'BPD Sulut' },
  { name: 'BPD Sumatera Barat', value: 'BPD Sumatera Barat' },
  { name: 'BPD Sumatera Barat UUS', value: 'BPD Sumatera Barat UUS' },
  { name: 'BPD Sumsel Dan Babel UUS', value: 'BPD Sumsel Dan Babel UUS' },
  { name: 'BPD Sumut', value: 'BPD Sumut' },
  { name: 'BPD Sumsel Dan Babel', value: 'BPD Sumsel Dan Babel' },
  { name: 'BPD Sumut UUS', value: 'BPD Sumut UUS' },
  { name: 'Centratama Nasional Bank', value: 'Centratama Nasional Bank' },
  { name: 'Citibank', value: 'Citibank' },
  { name: 'Deutsche Bank', value: 'Deutsche Bank' },
  { name: 'Hongkong and Shanghai Bank Corporation (HSBC)', value: 'Hongkong and Shanghai Bank Corporation (HSBC)' },
  {
    name: 'Hongkong and Shanghai Bank Corporation (HSBC) UUS',
    value: 'Hongkong and Shanghai Bank Corporation (HSBC) UUS'
  },
  { name: 'JP Morgan Chase Bank', value: 'JP Morgan Chase Bank' },
  { name: 'Prima Master Bank', value: 'Prima Master Bank' },
  { name: 'Royal Bank of Scotland (RBS)', value: 'Royal Bank of Scotland (RBS)' },
  { name: 'Standard Charted Bank', value: 'Standard Charted Bank' },
  { name: 'Bank Mitra Niaga', value: 'Bank Mitra Niaga' },
  { name: 'Indonesia Eximbank', value: 'Indonesia Eximbank' },
  { name: 'Bank Arta Niaga Kencana', value: 'Bank Arta Niaga Kencana' },
  { name: 'Bank Negara Indonesia (BNI)', value: 'Bank Negara Indonesia (BNI)' },
  { name: 'Bank Central Asia (BCA) Syariah', value: 'Bank Central Asia (BCA) Syariah' },
  { name: 'Bank Central Asia (BCA)', value: 'Bank Central Asia (BCA)' }
]
